# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RecruitBee' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RecruitBee
  pod 'Firebase'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'

  target 'RecruitBeeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
